# Generated by Django 2.1.1 on 2018-09-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
