# Generated by Django 2.1.1 on 2018-09-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0002_auto_20180903_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='have_pets',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='name',
        ),
        migrations.AddField(
            model_name='adress',
            name='have_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='places',
            name='handicapped_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='places',
            name='kitchen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='handicapped_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adress',
            name='email_alternative',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='languages',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='places.Adress'),
        ),
        migrations.RemoveField(
            model_name='places',
            name='rooms',
        ),
        migrations.AddField(
            model_name='places',
            name='rooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Rooms'),
        ),
    ]
