# Generated by Django 2.1.1 on 2018-09-03 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0004_auto_20180903_1308'),
    ]
    atomic = False,
