# Generated by Django 2.1.1 on 2018-09-03 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0006_auto_20180903_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='address',
        ),

    ]
