# Generated by Django 2.1.1 on 2018-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0008_auto_20180903_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.AddField(
            model_name='places',
            name='PlacePicture',
            field=models.ImageField(null=True, upload_to='', verbose_name='Picture of the place'),
        ),
        migrations.AlterField(
            model_name='places',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
