# Generated by Django 2.1.1 on 2018-09-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0009_auto_20180905_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='PlacePicture',
        ),
        migrations.RemoveField(
            model_name='places',
            name='address',
        ),
        migrations.RemoveField(
            model_name='places',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='places',
            name='pets_welcome',
        ),
        migrations.AddField(
            model_name='places',
            name='address_add',
            field=models.CharField(blank=True, help_text='Additional address information', max_length=200),
        ),
        migrations.AddField(
            model_name='places',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many bathrooms do you have?'),
        ),
        migrations.AddField(
            model_name='places',
            name='beds',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many beds do you have?'),
        ),
        migrations.AddField(
            model_name='places',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='places',
            name='common_kitchen',
            field=models.BooleanField(default=False,
                                      help_text='Do guests have access to your kitchen and can use it for preparing food?'),
        ),
        migrations.AddField(
            model_name='places',
            name='contact_first_name',
            field=models.CharField(blank=True, help_text='Your first name', max_length=100),
        ),
        migrations.AddField(
            model_name='places',
            name='contact_last_name',
            field=models.CharField(default='owner', help_text='Your last name', max_length=100),
        ),
        migrations.AddField(
            model_name='places',
            name='country',
            field=models.CharField(blank=True, help_text='Country Code', max_length=2),
        ),
        migrations.AddField(
            model_name='places',
            name='email',
            field=models.EmailField(default='hosttheway@gmail.com', help_text='Your contact email address',
                                    max_length=254),
        ),
        migrations.AddField(
            model_name='places',
            name='email_alt',
            field=models.EmailField(blank=True, help_text='Alternative email address', max_length=254),
        ),
        migrations.AddField(
            model_name='places',
            name='family',
            field=models.BooleanField(default=True, help_text='Is your house suitable families/kids?'),
        ),
        migrations.AddField(
            model_name='places',
            name='languages',
            field=models.CharField(default='EN', help_text='Which languages do you speak?', max_length=100),
        ),
        migrations.AddField(
            model_name='places',
            name='maximum_of_guests',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many guests can stay in yourt house?'),
        ),
        migrations.AddField(
            model_name='places',
            name='meals',
            field=models.CharField(
                choices=[('BR', 'only breakfast'), ('BL', 'breakfast and lunch'), ('BD', 'breakfast and dinner'),
                         ('AL', 'breakfast, lunch and dinner')], default='BR',
                help_text='How many melas per day your serve?', max_length=2),
        ),
        migrations.AddField(
            model_name='places',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number', max_length=20),
        ),
        migrations.AddField(
            model_name='places',
            name='outdoor_place',
            field=models.BooleanField(default=False, help_text='Do you have a garden, aterrace or a balcony?'),
        ),
        migrations.AddField(
            model_name='places',
            name='pets',
            field=models.BooleanField(default=True, help_text='Are peds wellcome?'),
        ),
        migrations.AddField(
            model_name='places',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=30),
        ),
        migrations.AddField(
            model_name='places',
            name='picture',
            field=models.ImageField(help_text='Picture of the place', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='places',
            name='private_bathroom',
            field=models.BooleanField(default=False, help_text='Do guests have a private bathroom?'),
        ),
        migrations.AddField(
            model_name='places',
            name='private_kitchen',
            field=models.BooleanField(default=False, help_text='Do guests have a private kitchen?'),
        ),
        migrations.AddField(
            model_name='places',
            name='room_add',
            field=models.CharField(blank=True, help_text='What other rooms can your guests use?', max_length=200),
        ),
        migrations.AddField(
            model_name='places',
            name='smoking',
            field=models.BooleanField(default=False, help_text='Is smoking allowed in the house?'),
        ),
        migrations.AddField(
            model_name='places',
            name='street',
            field=models.CharField(blank=True, help_text='Street', max_length=100),
        ),
        migrations.AddField(
            model_name='places',
            name='who_lives_here',
            field=models.CharField(blank=True, help_text='Who lives in your house?', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(default='hosttheway@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='places',
            name='description',
            field=models.CharField(default='', help_text='Describe your place', max_length=400),
        ),
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(help_text='Name of your place', max_length=200),
        ),
        migrations.AlterField(
            model_name='places',
            name='rooms',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many rooms do you rent?'),
        ),
    ]
