# Generated by Django 2.1.1 on 2018-09-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0012_auto_20180919_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='picture',
            field=models.ImageField(default='hosttheway.jpg', height_field=200, help_text='Picture of your place',
                                    upload_to='', width_field=200),
        ),
    ]
