# Generated by Django 2.1.1 on 2018-09-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0015_geoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Link to the available towns or areas', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='places.GeoName'),
        ),
    ]
