# Generated by Django 2.1.1 on 2018-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0017_auto_20181002_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='picture',
            field=models.ImageField(blank=True, help_text='Picture of your place', upload_to=''),
        ),
    ]
