# Generated by Django 2.1.1 on 2018-10-08 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0019_auto_20181008_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='price_breakfast',
        ),
        migrations.RemoveField(
            model_name='place',
            name='price_meal',
        ),
    ]
