# Generated by Django 2.1.1 on 2018-10-08 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0020_auto_20181008_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='valid_from',
            field=models.DateField(default=datetime.date(2018, 1, 1), help_text='Price is valid from this date'),
        ),
        migrations.AddField(
            model_name='price',
            name='valid_to',
            field=models.DateField(default=datetime.date(2018, 12, 31), help_text='Price is valid to this date'),
        ),
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.CharField(choices=[('CN', 'Regular price per night'), ('CR', 'Regular price per room'),
                                            ('BN', 'Special price per night'), ('BR', 'Special price per room'),
                                            ('AN', 'Top price per night'), ('AR', 'Top price per room'),
                                            ('CL', 'Cleaning fee'), ('BR', 'Price for breakfast'),
                                            ('BL', 'Price for breakfast and lunch'),
                                            ('BD', 'Price for breakfast and dinner'), ('AM', 'Price for three meals')],
                                   default='CN', help_text='Waht kind of contact you can offer your guest?',
                                   max_length=2),
        ),
    ]
