# Generated by Django 2.1.1 on 2018-10-09 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0021_auto_20181008_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(default='01', help_text='Room number/identifier', max_length=50)),
                ('beds', models.PositiveIntegerField(default=2, help_text='Number of beds in this room')),
                ('price_per_person',
                 models.DecimalField(decimal_places=2, default=0.0, help_text='Price for the current category',
                                     max_digits=9)),
                ('price_per_room',
                 models.DecimalField(decimal_places=2, default=0.0, help_text='Price for the current category',
                                     max_digits=9)),
                ('currency', models.CharField(default='EUR', help_text='Currency ISO 3 Code', max_length=3)),
                ('valid_from',
                 models.DateField(default=datetime.date(2018, 1, 1), help_text='Price is valid from this date')),
                ('valid_to',
                 models.DateField(default=datetime.date(2018, 12, 31), help_text='Price is valid to this date')),
                ('bathroom', models.BooleanField(default=True, help_text='Do this room have a private bathroom?')),
                ('kitchen', models.BooleanField(default=False, help_text='Do this room  have a private kitchen?')),
                ('outdoor_place',
                 models.BooleanField(default=False, help_text='Do this room have a garden, a terrace or a balcony?')),
                ('room_add',
                 models.CharField(blank=True, help_text='Additional information about this room', max_length=200)),
                ('smoking', models.BooleanField(default=False, help_text='Smoking allowed in the room?')),
                ('pets', models.BooleanField(default=True, help_text='Are peds welcome?')),
                ('family', models.BooleanField(default=True, help_text='Is this room suitable families/kids?')),
                ('handicapped_enabled',
                 models.BooleanField(default=False, help_text='Is this room suitable for handicapped guests?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reviewed', models.BooleanField(default=False, editable=False)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.Place')),
            ],
        ),
        migrations.RenameField(
            model_name='price',
            old_name='place_id',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.CharField(choices=[('CN', 'Regular price per night'), ('CR', 'Regular price per room'),
                                            ('BN', 'Special price per night'), ('BR', 'Special price per room'),
                                            ('AN', 'Top price per night'), ('AR', 'Top price per room'),
                                            ('CL', 'Cleaning fee'), ('BR', 'Price for breakfast'),
                                            ('BL', 'Price for breakfast and lunch'),
                                            ('BD', 'Price for breakfast and dinner'), ('AM', 'Price for three meals')],
                                   default='CN', help_text='What kind of contact you can offer your guest?',
                                   max_length=2),
        ),
    ]
