# Generated by Django 2.1.1 on 2018-10-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0022_auto_20181009_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='description',
            field=models.CharField(blank=True, default='', help_text='WDescription of this price', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for the current category',
                                      max_digits=9, max_length=12),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_room',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for the current category',
                                      max_digits=9, max_length=12),
        ),
    ]
