# Generated by Django 2.1.1 on 2018-10-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0023_auto_20181010_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.CharField(choices=[('CN', 'Regular price per night'), ('CR', 'Regular price per room'),
                                            ('BN', 'Special price per night'), ('BR', 'Special price per room'),
                                            ('AN', 'Top price per night'), ('AR', 'Top price per room'),
                                            ('CL', 'Cleaning fee'), ('BR', 'Price for breakfast'),
                                            ('BL', 'Price for breakfast and lunch'),
                                            ('BD', 'Price for breakfast and dinner'), ('AM', 'Price for three meals')],
                                   default='CL', help_text='What kind of contact you can offer your guest?',
                                   max_length=2),
        ),
        migrations.AlterField(
            model_name='price',
            name='description',
            field=models.CharField(default='', help_text='Description of this price', max_length=100),
        ),
    ]
