# Generated by Django 2.1.1 on 2018-10-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0024_auto_20181011_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='description',
            field=models.CharField(blank=True, help_text='Description of this price', max_length=100),
        ),
    ]
