# Generated by Django 2.1.1 on 2018-10-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('places', '0025_auto_20181011_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.CharField(choices=[('CN', 'Regular price per night'), ('CR', 'Regular price per room'),
                                            ('BN', 'Special price per night'), ('BR', 'Special price per room'),
                                            ('AN', 'Top price per night'), ('AR', 'Top price per room'),
                                            ('CL', 'Cleaning fee'), ('BR', 'Price for breakfast'),
                                            ('BL', 'Price for breakfast and lunch'),
                                            ('BD', 'Price for breakfast and dinner'), ('AM', 'Price for three meals')],
                                   default='CL', help_text='For what is the price for?', max_length=2),
        ),
    ]
