# Generated by Django 2.1.1 on 2018-10-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0027_auto_20181017_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='priority_category',
            field=models.CharField(blank=True, choices=[('NA', 'No special category'), ('AW', 'Alwasy on top')],
                                   default='NA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='priority_value',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
