# Generated by Django 2.1.1 on 2018-10-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0029_auto_20181017_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='place',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='place',
            name='family',
        ),
        migrations.RemoveField(
            model_name='place',
            name='handicapped_enabled',
        ),
        migrations.RemoveField(
            model_name='place',
            name='maximum_of_guests',
        ),
        migrations.RemoveField(
            model_name='place',
            name='pets',
        ),
        migrations.RemoveField(
            model_name='place',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='place',
            name='smoking',
        ),
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, help_text='Website of the place'),
        ),
        migrations.AlterField(
            model_name='geoname',
            name='alternate_names',
            field=models.CharField(
                help_text='comma separated, ascii names automatically transliterated, convenience attribute from alternate name table',
                max_length=1000),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(blank=True, default='', help_text='What else would you like to tell your guests?',
                                   max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Where is your place (latitude)?', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Where is your place (longitude)?', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='min_stay',
            field=models.PositiveIntegerField(default=1, help_text='What is the minimum stay?'),
        ),
        migrations.AlterField(
            model_name='place',
            name='priority_value',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AlterField(
            model_name='room',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
