# Generated by Django 2.1.1 on 2018-10-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0030_auto_20181023_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='price',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='price',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='currency',
        ),
        migrations.AddField(
            model_name='place',
            name='currency',
            field=models.CharField(default='EUR', help_text='Currency ISO 3 Code', max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='category',
            field=models.CharField(
                choices=[('CL', 'Cleaning fee'), ('BR', 'Price for breakfast'), ('BL', 'Price for breakfast and lunch'),
                         ('BD', 'Price for breakfast and dinner'), ('AM', 'Price for three meals')], default='CL',
                help_text='For what is the price for?', max_length=2),
        ),
    ]
