# Generated by Django 2.1.1 on 2018-10-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0031_auto_20181023_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('TI', 'One room to rent with 2 beds'), ('SM', 'Two rooms with 2-3 beds'),
                                            ('ME', 'Three rooms with 2-6 beds'), ('LA', 'Four rooms with 2-6 beds'),
                                            ('HO', 'More than four rooms to rent '), ('NA', 'n/a')], default='NA',
                                   help_text='Category of your place', max_length=2),
        ),
        migrations.AlterField(
            model_name='place',
            name='priority_category',
            field=models.CharField(blank=True, choices=[('NA', 'No special category'), ('AW', 'Always on top')],
                                   default='NA', max_length=2, null=True),
        ),
    ]
