# Generated by Django 2.1.2 on 2018-11-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0032_auto_20181024_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
