# Generated by Django 2.1.2 on 2018-11-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0033_auto_20181107_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, default='', help_text='What else would you like to tell your guests?',
                                   max_length=1024),
        ),
    ]
