# Generated by Django 2.1.5 on 2019-01-30 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0034_auto_20181113_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pets',
            field=models.BooleanField(default=True, help_text='Are pets welcome?'),
        ),
        migrations.AlterField(
            model_name='room',
            name='valid_from',
            field=models.DateField(default=datetime.date(2019, 1, 1), help_text='Price is valid from this date'),
        ),
        migrations.AlterField(
            model_name='room',
            name='valid_to',
            field=models.DateField(default=datetime.date(2019, 12, 31), help_text='Price is valid to this date'),
        ),
    ]
