# Generated by Django 2.1.5 on 2019-02-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0036_auto_20190214_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('place_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='places.Place')),
            ],
            bases=('places.place',),
        ),
    ]
