# Generated by Django 2.1.5 on 2019-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0037_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
