# Generated by Django 2.1.2 on 2018-11-14 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=64, null=True)),
                ('zip', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile', models.CharField(blank=True, max_length=64, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('alt_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('deleted', models.BooleanField(default=False)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
