# Generated by Django 2.1.5 on 2019-02-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0037_hostel'),
        ('article', '0002_textarticle_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagearticle',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='textarticle',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='imagearticle',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagearticle',
            name='picture',
            field=models.ImageField(help_text='Picture of your place', upload_to='%Y/%m/%d/'),
        ),
    ]
