# Generated by Django 2.1.5 on 2019-02-15 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('article', '0003_auto_20190214_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagearticle',
            name='place',
        ),
        migrations.RemoveField(
            model_name='imagearticle',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='textarticle',
            name='place',
        ),
        migrations.RemoveField(
            model_name='textarticle',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='imagearticle',
            name='country',
            field=models.CharField(blank=True, help_text='Country Code', max_length=2),
        ),
        migrations.AddField(
            model_name='imagearticle',
            name='currency',
            field=models.CharField(default='EUR', help_text='Currency ISO 3 Code', max_length=3),
        ),
        migrations.AddField(
            model_name='imagearticle',
            name='description',
            field=models.TextField(blank=True, default='', help_text='What else would you like to tell your guests?',
                                   max_length=1024),
        ),
        migrations.AddField(
            model_name='imagearticle',
            name='name',
            field=models.CharField(default='image', help_text='Name of your place', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textarticle',
            name='country',
            field=models.CharField(blank=True, help_text='Country Code', max_length=2),
        ),
        migrations.AddField(
            model_name='textarticle',
            name='currency',
            field=models.CharField(default='EUR', help_text='Currency ISO 3 Code', max_length=3),
        ),
        migrations.AddField(
            model_name='textarticle',
            name='description',
            field=models.TextField(blank=True, default='', help_text='What else would you like to tell your guests?',
                                   max_length=1024),
        ),
        migrations.AddField(
            model_name='textarticle',
            name='name',
            field=models.CharField(default='text', help_text='Name of your place', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagearticle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagearticle',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='textarticle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='textarticle',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
