# Generated by Django 2.1.5 on 2019-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('article', '0004_auto_20190215_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagearticle',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='textarticle',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
