# Generated by Django 2.1.5 on 2019-02-15 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('article', '0005_auto_20190215_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagearticle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='imagearticle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='textarticle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='textarticle',
            name='name',
        ),
    ]
