# Generated by Django 2.1.5 on 2019-02-15 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('article', '0006_auto_20190215_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagearticle',
            name='country',
        ),
        migrations.RemoveField(
            model_name='imagearticle',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='textarticle',
            name='country',
        ),
        migrations.RemoveField(
            model_name='textarticle',
            name='currency',
        ),
    ]
