# Generated by Django 2.1.5 on 2019-01-30 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0002_auto_20190130_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='traveller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
