# Generated by Django 2.1.2 on 2018-11-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('traveller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
