# Generated by Django 2.1.3 on 2018-11-19 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traveller', '0002_auto_20181114_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='permission',
            field=models.ManyToManyField(related_name='place_permission', to=settings.AUTH_USER_MODEL),
        ),
    ]
