# Generated by Django 2.1.3 on 2018-11-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('traveller', '0002_auto_20181123_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='user',
            name='screen_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='screen name'),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_name',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='unique name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email already exists.'}, max_length=254,
                                    unique=True, verbose_name='email address'),
        ),
    ]
