# Generated by Django 2.1.3 on 2018-11-23 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('traveller', '0003_auto_20181123_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='screen_name',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='screen name'),
        ),
    ]
