# Generated by Django 2.1.3 on 2018-11-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('traveller', '0003_traveller_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='permission',
            field=models.ManyToManyField(related_name='place_permission', to='places.Place'),
        ),
    ]
