# Generated by Django 2.1.3 on 2018-11-19 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('traveller', '0004_auto_20181119_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='permission',
        ),
    ]
