# Generated by Django 2.1.3 on 2018-11-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('traveller', '0004_auto_20181123_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
