# Generated by Django 2.1.3 on 2018-11-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0034_auto_20181113_1323'),
        ('traveller', '0005_remove_traveller_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='permission',
            field=models.ManyToManyField(related_name='place_permission', to='places.Place'),
        ),
    ]
