# Generated by Django 2.1.3 on 2018-11-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0034_auto_20181113_1323'),
        ('traveller', '0006_traveller_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='permission',
        ),
        migrations.AddField(
            model_name='traveller',
            name='place_permission',
            field=models.ManyToManyField(to='places.Place'),
        ),
    ]
