# Generated by Django 2.1.3 on 2018-11-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0034_auto_20181113_1323'),
        ('traveller', '0007_auto_20181119_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                            to='places.Place')),
            ],
        ),
        migrations.RemoveField(
            model_name='traveller',
            name='place_permission',
        ),
        migrations.AddField(
            model_name='traveller',
            name='place_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='traveller.PlaceAccount'),
        ),
    ]
